# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingREST', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='roll1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll17',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll18',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll19',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll20',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll21',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roll9',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
