# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_value', models.SlugField(blank=True, default='', max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'created'), (2, 'sent'), (3, 'completed')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='ratingquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='survey.Survey'),
        ),
    ]
