# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
                ('attempt3', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Frame9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.CharField(default='', max_length=2)),
                ('attempt2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='frame9',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame8',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame7',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame6',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame5',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame4',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame3',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame2',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame10',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='frame1',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
    ]
