# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame1',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame10',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame2',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame3',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame4',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame5',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame6',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame7',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame8',
            name='game',
        ),
        migrations.RemoveField(
            model_name='frame9',
            name='game',
        ),
        migrations.DeleteModel(
            name='Frame1',
        ),
        migrations.DeleteModel(
            name='Frame10',
        ),
        migrations.DeleteModel(
            name='Frame2',
        ),
        migrations.DeleteModel(
            name='Frame3',
        ),
        migrations.DeleteModel(
            name='Frame4',
        ),
        migrations.DeleteModel(
            name='Frame5',
        ),
        migrations.DeleteModel(
            name='Frame6',
        ),
        migrations.DeleteModel(
            name='Frame7',
        ),
        migrations.DeleteModel(
            name='Frame8',
        ),
        migrations.DeleteModel(
            name='Frame9',
        ),
    ]
