# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0003_auto_20171012_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='attempt2',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='frame',
            name='attempt3',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
