# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0004_auto_20171012_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.CharField(default='', max_length=50),
        ),
    ]
