# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0006_game_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
