# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0007_auto_20171012_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='frame1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame10',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame8',
        ),
        migrations.RemoveField(
            model_name='game',
            name='frame9',
        ),
    ]
