# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0008_auto_20171012_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='counter',
        ),
    ]
