# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0011_auto_20171015_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='attempt1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='bowling.Game'),
        ),
    ]
