# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0012_auto_20171016_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date ended'),
        ),
        migrations.AddField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date started'),
        ),
    ]
